# Generated by Django 5.0 on 2026-03-22 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolleyballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_joined', models.DateField()),
                ('position', models.CharField(choices=[('SETTER', 'Setter'), ('OUTSIDE', 'Outside Hitter'), ('MIDDLE', 'Middle Blocker'), ('OPPOSITE', 'Opposite Hitter'), ('LIBERO', 'Libero')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('contact_person', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
